package com.app.wxapi.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmMemberCards<M extends BaseCrmMemberCards<M>> extends Model<M> implements IBean {

    public M setId(java.lang.Integer id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.Integer getId() {
        return get("id");
    }

    public M setCardName(java.lang.String cardName) {
        set("card_name", cardName);
        return (M) this;
    }

    public java.lang.String getCardName() {
        return get("card_name");
    }

    public M setDiscount(java.lang.Integer discount) {
        set("discount", discount);
        return (M) this;
    }

    public java.lang.Integer getDiscount() {
        return get("discount");
    }

    public M setIntegral(java.lang.Integer integral) {
        set("integral", integral);
        return (M) this;
    }

    public java.lang.Integer getIntegral() {
        return get("integral");
    }

    public M setBalance(java.lang.Integer balance) {
        set("balance", balance);
        return (M) this;
    }

    public java.lang.Integer getBalance() {
        return get("balance");
    }

    public M setCurrency(java.lang.String currency) {
        set("currency", currency);
        return (M) this;
    }

    public java.lang.String getCurrency() {
        return get("currency");
    }

    public M setValidTermType(java.lang.Long validTermType) {
        set("valid_term_type", validTermType);
        return (M) this;
    }

    public java.lang.Long getValidTermType() {
        return get("valid_term_type");
    }

    public M setValidTermCount(java.lang.Integer validTermCount) {
        set("valid_term_count", validTermCount);
        return (M) this;
    }

    public java.lang.Integer getValidTermCount() {
        return get("valid_term_count");
    }

    public M setValidTermFrom(java.util.Date validTermFrom) {
        set("valid_term_from", validTermFrom);
        return (M) this;
    }

    public java.util.Date getValidTermFrom() {
        return get("valid_term_from");
    }

    public M setValidTermTo(java.util.Date validTermTo) {
        set("valid_term_to", validTermTo);
        return (M) this;
    }

    public java.util.Date getValidTermTo() {
        return get("valid_term_to");
    }

    public M setStartFrom(java.lang.String startFrom) {
        set("start_from", startFrom);
        return (M) this;
    }

    public java.lang.String getStartFrom() {
        return get("start_from");
    }

    public M setQuantity(java.lang.Integer quantity) {
        set("quantity", quantity);
        return (M) this;
    }

    public java.lang.Integer getQuantity() {
        return get("quantity");
    }

    public M setUsedQuantity(java.lang.Integer usedQuantity) {
        set("used_quantity", usedQuantity);
        return (M) this;
    }

    public java.lang.Integer getUsedQuantity() {
        return get("used_quantity");
    }

    public M setStatus(java.lang.Long status) {
        set("status", status);
        return (M) this;
    }

    public java.lang.Long getStatus() {
        return get("status");
    }

    public M setComment(java.lang.String comment) {
        set("comment", comment);
        return (M) this;
    }

    public java.lang.String getComment() {
        return get("comment");
    }

    public M setTenantId(java.lang.Integer tenantId) {
        set("tenant_id", tenantId);
        return (M) this;
    }

    public java.lang.Integer getTenantId() {
        return get("tenant_id");
    }

    public M setCreateDate(java.util.Date createDate) {
        set("create_date", createDate);
        return (M) this;
    }

    public java.util.Date getCreateDate() {
        return get("create_date");
    }

    public M setCreateBy(java.lang.String createBy) {
        set("create_by", createBy);
        return (M) this;
    }

    public java.lang.String getCreateBy() {
        return get("create_by");
    }

    public M setUpdateDate(java.util.Date updateDate) {
        set("update_date", updateDate);
        return (M) this;
    }

    public java.util.Date getUpdateDate() {
        return get("update_date");
    }

    public M setUpdateBy(java.lang.String updateBy) {
        set("update_by", updateBy);
        return (M) this;
    }

    public java.lang.String getUpdateBy() {
        return get("update_by");
    }

}
