package com.app.wxapi.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFavorites<M extends BaseFavorites<M>> extends Model<M> implements IBean {

    public M setId(java.lang.Integer id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.Integer getId() {
        return get("id");
    }

    public M setBarcode(java.lang.String barcode) {
        set("barcode", barcode);
        return (M) this;
    }

    public java.lang.String getBarcode() {
        return get("barcode");
    }

    public M setPic(java.lang.String pic) {
        set("pic", pic);
        return (M) this;
    }

    public java.lang.String getPic() {
        return get("pic");
    }

    public M setCreateDate(java.util.Date createDate) {
        set("createDate", createDate);
        return (M) this;
    }

    public java.util.Date getCreateDate() {
        return get("createDate");
    }

    public M setCreateUserid(java.lang.String createUserid) {
        set("createUserid", createUserid);
        return (M) this;
    }

    public java.lang.String getCreateUserid() {
        return get("createUserid");
    }

    public M setModifyDate(java.util.Date modifyDate) {
        set("modifyDate", modifyDate);
        return (M) this;
    }

    public java.util.Date getModifyDate() {
        return get("modifyDate");
    }

    public M setModifyUserid(java.lang.String modifyUserid) {
        set("modifyUserid", modifyUserid);
        return (M) this;
    }

    public java.lang.String getModifyUserid() {
        return get("modifyUserid");
    }

}
