package com.app.wxapi.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmMemcardsApplyRange<M extends BaseCrmMemcardsApplyRange<M>> extends Model<M> implements IBean {

    public M setId(java.lang.Integer id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.Integer getId() {
        return get("id");
    }

    public M setCardsId(java.lang.Integer cardsId) {
        set("cards_id", cardsId);
        return (M) this;
    }

    public java.lang.Integer getCardsId() {
        return get("cards_id");
    }

    public M setTargetId(java.lang.Integer targetId) {
        set("target_id", targetId);
        return (M) this;
    }

    public java.lang.Integer getTargetId() {
        return get("target_id");
    }

}
