package com.app.wxapi.model;

import com.app.wxapi.model.memberinfo.MemberInfo;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.weixin.model.Order;

/**
 * Generated by JFinal, do not modify this file.
 * <p>
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

    public static void mapping(ActiveRecordPlugin arp) {
        arp.addMapping("crm_sequence", "name", Sequence.class);
        arp.addMapping("crm_member_cards", "id", MemberCards.class);
        arp.addMapping("crm_member_info", "id", MemberInfo.class);
        arp.addMapping("crm_memcards_apply_range", "id", MemcardsApplyRange.class);
        arp.addMapping("crm_sequence", "name", Sequence.class);
        arp.addMapping("crm_member_favorites", "id", Favorites.class);
        arp.addMapping("b_order", Order.class);
        arp.addMapping("crm_app_info", AppInfo.class);
    }
}
