package com.app.wxapi.model;

import com.app.wxapi.model.base.BaseFavorites;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Favorites extends BaseFavorites<Favorites> {
    public String picdateStr;

    public String getPicdateStr() {
        return picdateStr;
    }

    public void setPicdateStr(String picdateStr) {
        this.picdateStr = picdateStr;
    }
}
