package com.app.wxapi.model;

import com.app.wxapi.model.base.BaseMemberCards;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberCards extends BaseMemberCards<MemberCards> {
    public static final MemberCards dao = new MemberCards().dao();
}
