package com.app.wxapi.model;

import com.app.wxapi.model.base.BaseMemcardsApplyRange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemcardsApplyRange extends BaseMemcardsApplyRange<MemcardsApplyRange> {
    public static final MemcardsApplyRange dao = new MemcardsApplyRange().dao();
}
