package com.app.wxapi.model;

import com.app.wxapi.model.base.BaseSequence;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sequence extends BaseSequence<Sequence> {
    public static final Sequence dao = new Sequence().dao();
}
